language: c
sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 }
    - { os: linux, env: PYTHON_VERSION=3.4 }
    - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: osx, env: PYTHON_VERSION=2.7 }
    - { os: osx, env: PYTHON_VERSION=3.4 }
    - { os: osx, env: PYTHON_VERSION=3.5 }

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install_conda.sh

  - conda config --set always_yes yes --set changeps1 no
  - conda env create -q -n test-environment python=$PYTHON_VERSION -f devtools/conda-ens/test_env.yml
  - source activate test-environment
  - pip install -e .

script:
  - py.test -v --pyargs intermol
